---
- name: Install Development Packages
  hosts: localhost
  become: true
  tasks:
    - name: Install development packages
      apt:
        pkg:
          - ack
          - automake
          - build-essential
          - curl
          - make
          - wxhexeditor
        state: present

- name: Install Development Tools
  hosts: localhost
  roles:
    - git
    - intellij-idea
    - docker

