---
- name: Install Additional Packages
  hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - bzip2
        - flashplugin-installer
        - gimp
        - gstreamer1.0-gtk3
        - gstreamer1.0-libav
        - gstreamer1.0-fluendo-mp3
        - keepassx
        - libreoffice
        - synaptic
        - tree
        - vlc

- name: Install Other Software
  hosts: localhost
  roles:
    - chrome
    - power-management
    - virtualbox

