---
- name: Install Additional Packages
  hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt:
        pkg:
          - bzip2
          - flashplugin-installer
          - gimp
          - gstreamer1.0-gtk3
          - gstreamer1.0-libav
          - gstreamer1.0-fluendo-mp3
          - keepassxc
          - libreoffice
          - synaptic
          - tree
          - vlc
        state: present

- name: Install Other Software
  hosts: localhost
  roles:
    - chrome
    - power-management
    - virtualbox

