- name: bash
  src: https://github.com/deanmcniven/ansible-bash
  version: origin/master

- name: chrome
  src: https://github.com/deanmcniven/ansible-chrome
  version: origin/master

- name: docker
  src: https://github.com/deanmcniven/ansible-docker
  version: origin/master

- name: git
  src: https://github.com/deanmcniven/ansible-git
  version: origin/master

- name: gnome-avatar
  src: https://github.com/deanmcniven/ansible-gnome-avatar
  version: origin/master

- name: gnome-desktop
  src: https://github.com/deanmcniven/ansible-gnome-desktop
  version: origin/master

- name: gnome-terminal
  src: https://github.com/deanmcniven/ansible-gnome-terminal
  version: origin/master

- name: intellij-idea
  src: https://github.com/deanmcniven/ansible-intellij-idea
  version: origin/master

- name: power-management
  src: https://github.com/deanmcniven/ansible-power-management
  version: origin/master

- name: tmux
  src: https://github.com/deanmcniven/ansible-tmux
  version: origin/master

- name: vim
  src: https://github.com/deanmcniven/ansible-vim
  version: origin/master
