- name: git
  src: https://github.com/deanmcniven/ansible-git
  version: origin/master
- name: intellij-idea
  src: https://github.com/deanmcniven/ansible-intellij-idea
  version: origin/master
- name: vim
  src: https://github.com/deanmcniven/ansible-vim
  version: origin/master
