---
- hosts: localhost
  become: true
  tasks:
    - name: Apt Update
      apt: update_cache=yes
      changed_when: false

- name: Install Development Tools
  hosts: localhost
  roles:
    - intellij-idea
